# Configuration file for movie sentiment analysis project

default:
  main_logging:
    handler: "file"
    path: "assets/logs/app.log"
  log_directories:
    base: "assets/logs"
    temp_prediction: "assets/logs/temp_prediction_logs.json"
    fallback_prediction: "assets/logs/prediction_logs_fallback.json"
  model_directories:
    base: "assets/models"
    temp: "base"
  data_directories:
    base: "assets/data"
  kaggle:
    dataset_path: "julian3833/jigsaw-toxic-comment-classification-challenge"
    dataset_name: "train.csv"

development:
  paths: # Local file paths
    data: "assets/data/train.csv"
    model: "assets/models/toxic_model.pkl"
    model_metadata: "assets/models/toxic_model_metadata.json"
  prediction_logging:
    handler: "file"
    path: "assets/logs/prediction_logs.json"
  mlflow: # MLflow tracking via remote server
    tracking_uri: "http://mlflow-server:5000"
    experiment_name: "toxic-comments-classification"

production:
  paths: # S3 paths
    data: "data/train.csv"
    model: "models/toxic_model.pkl"
    model_metadata: "models/toxic_model_metadata.json"
  prediction_logging:
    handler: "dynamodb"
    table_name: "prediction_logs"
  mlflow: # MLflow tracking via remote server with PostgreSQL backend
    tracking_uri: "http://MLFLOW_SERVER_IP:5000"  # Will be replaced with actual IP in deployment
    experiment_name: "toxic-comments-classification-prod"
    artifact_root: "s3://BUCKET_NAME/mlflow-artifacts"  # Will be replaced with actual bucket name
